# Generated by Django 2.2.8 on 2020-03-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogv1', '0006_auto_20200301_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogv1',
            options={'ordering': ['-created_time']},
        ),
    ]
