# Generated by Django 2.2.8 on 2020-03-04 07:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogv1', '0008_auto_20200304_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogv1',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
