# Generated by Django 2.2.8 on 2020-03-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogv1', '0009_auto_20200304_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogv1',
            name='read_num',
        ),
    ]
