# Generated by Django 2.2.8 on 2020-03-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogv1', '0010_remove_blogv1_read_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogv1',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogv1',
            name='blog_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogv1.BlogType'),
        ),
    ]
